export type Permission =
    |'car:view'
|'car:add'
|'car:update'
|'car:archive'
|'car:delete'
|'rental:create'
|'rental:cancel'
|'rental:view'
|'rental:update'
|'payment:view'
|'payment:process'
|'user:updateProfile'
|'user:changeRole'
|'user:manage'
|'log:view'
|'system:config'